language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -U pip setuptools
  - pip install -e .[ci]

script:
  - pytest --cov=django_crossdb_foreignkey --cov-report term-missing:skip-covered tests

after_success:
  - coveralls