# Generated by Django 2.2.3 on 2019-07-04 08:06

from django.db import migrations, models
import django_crossdb_foreignkey.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='OtherManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('department', django_crossdb_foreignkey.fields.CrossDBOneToOneField(related_name='manager', to='example_models.Department')),
            ],
        ),
        migrations.CreateModel(
            name='OtherEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('department', django_crossdb_foreignkey.fields.CrossDBForeignKey(related_name='employees', to='example_models.Department')),
            ],
        ),
    ]
