# Generated by Django 2.2.3 on 2019-07-04 10:00

from django.db import migrations, models
import django_crossdb_foreignkey.fields


class Migration(migrations.Migration):

    dependencies = [
        ('example_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('department', django_crossdb_foreignkey.fields.CrossDBOneToOneField(related_name='+', to='example_models.Department')),
            ],
        ),
    ]
