# Generated by Django 2.2.3 on 2019-07-04 10:28

from django.db import migrations, models
import django_crossdb_foreignkey.fields


class Migration(migrations.Migration):

    dependencies = [
        ('example_models', '0002_othersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherHeadOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', django_crossdb_foreignkey.fields.CrossDBOneToOneField(null=True, related_name='head_office', to='example_models.Department')),
            ],
        ),
    ]
